[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "agno"
version = "0.1.0"
description = "A framework for building AI agents"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.0.0",
    "anthropic>=0.8.0",
] 