name: LinkedIn Content Generation

on:
  schedule:
    - cron: '0 0 * * 1'  # Run at midnight every Monday
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-content:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd /home/runner/work/wmarkus-agent-automation/wmarkus-agent-automation
        pip install -e .  # Install package in development mode
        pip install -r requirements.txt
    
    - name: Generate LinkedIn content
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
      run: |
        cd /home/runner/work/wmarkus-agent-automation/wmarkus-agent-automation
        python -c "import agno; print('Agno package found')"  # Verify package installation
        python linkedIN.py --save --email
        
    - name: Send email with content
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.FROM_EMAIL }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: LinkedIn Content for Today
        body: file://linkedin_content/linkedin_content_ideas_$(date +%Y-%m-%d).md
        to: ${{ secrets.TO_EMAIL }}
        from: ${{ secrets.FROM_EMAIL }}
        content_type: text/markdown 